format = """
$custom\
$battery\
$time\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$lua\
$jobs\
$git_branch\
$git_commit\
$git_state\
$git_status\

$line_break\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$status\
$character\
"""

[character]
success_symbol = "[îŠ…](bold green)"
vicmd_symbol = "[ï‹](bold yellow)"
error_symbol = "[ï€](bold red)"

[custom.battery100]
command = "acpi | awk '{print $4}' | sed 's/,//g'"
symbol = "ï‰€  "
style = "green"
format = "[$symbol$output]($style) "
when = "battery100"
shell = ["bash"]

[custom.battery75]
command = "acpi | awk '{print $4}' | sed 's/,//g'"
symbol = "ï‰  "
style = "green"
format = "[$symbol$output]($style) "
when = "battery75"
shell = ["bash"]

[custom.battery50]
command = "echo hi"
symbol = "ï‰‚  "
style = "yellow"
format = "[$symbol$output]($style) "
when = "battery50"
shell = ["bash"]

[custom.battery25]
command = "acpi | awk '{print $4}' | sed 's/,//g'"
symbol = "ï‰ƒ  "
style = "red"
format = "[$symbol$output]($style) "
when = "battery25"
shell = ["bash"]

[custom.battery10]
command = "acpi | awk '{print $4}' | sed 's/,//g'"
symbol = "ï‰„  "
style = "bold red"
format = "[$symbol$output]($style) "
when = "battery10"
shell = ["bash"]

[battery]
disabled = true

[cmd_duration]
min_time = 10_000
format = "ï¨š[$duration]($style) "

[time]
time_format = "%I:%M%p"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false

[python]
format = '[${symbol}${pyenv_prefix}${version} (\($virtualenv\))]($style) '

[package]
disabled = true

[jobs]
symbol = "ï‰’"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style)) '
style = "bright-white"
conflicted = "ï«• "
ahead = "ï¤˜Ã—${count} "
behind = "ï¡¶ Ã—${count} "
diverged = "ï­€ ï¤˜ Ã—${ahead_count} ï¡¶ Ã—${behind_count} "
modified = "ï‘ˆ Ã—${count} "
untracked = "ï¬’ Ã—${count} "
stashed = "ï¬š  " 
staged = "ï± Ã—${count} "
renamed = "î‰¼ Ã—${count} "
deleted = "ï’ Ã—${count} "

[username]
show_always = true
style_user = "bold cyan"
format = "[$user]($style)@"

[hostname]
ssh_only = false
format = "[$hostname](blue): "

[directory]
fish_style_pwd_dir_length = 1
read_only = " ï€£"
